### ISSUE TITLE
Not working on LG49UB820

### ISSUE THREAD

**Issue by rridder** [lrusak/lrusak-openelec-addons#1]
Hello, 
nice addon, hope you can make it work. For me it's not working.
Could this be because it behind a receiver?

**Comment by lrusak** [comment]
I'm sorry if the wetek-cec add-on isn't working for you. It seems to have limited capabilities with certain TV's.

Feel free to post some logs though and we can have a look.
http://wiki.openelec.tv/index.php/OpenELEC_FAQ#How_do_I_generate_support_logs.3F
