### ISSUE TITLE
CEC doesn't work properly sometimes

### ISSUE THREAD

**Issue by Goga777** [lrusak/lrusak-openelec-addons#12]
with kodi 17 beta1 CEC worked properly with my Harmann AVR171 and TV Samsung. I didn't use your addon. But with latest version of LE CEC doesn't work correctly sometime. I have installed your addon and it didn't help. If I switched off/on my  wetek play, than nothing happens - TV & AVR didn't switch off/on. If I will switch off TV my wetek play will switch off as well, but AVR didn't switch off. If I will swich ON my TV than nothing happened - wetek didn't switch ON.

 Also there is other bug - after restart of my wetel AVR device is switched off - see the log for 22:03

Also in log there are a lot of errors as ERROR: CecLogMessage - Write: write failed 

my log here is http://slexy.org/view/s2mj1sHLLA

If on wetek screensaver will activate/deactivate then AVR & TV switched off/on correctly.

**Comment by Goga777** [comment]
http://slexy.org/view/s2SAShBOAQ
here is sample, when after start up of the kodi my AVR twice swithed off/on by unknown reason. Also in that log you can see - after activation/deactivation of screensaver AVR & TV switched off/on correctly. Only one problemstill exists - during wetek shutdown/start TV & AVR doesn't shutdown/start.

**Comment by lrusak** [comment]
The add-on isn't relevant anymore with the new amlogic CEC driver.
