### ISSUE TITLE
lrusak repo offers outdated docker

### ISSUE THREAD

**Issue by phillipao** [lrusak/lrusak-openelec-addons#13]
To repro:
1. Download lrusak repo
2. Install docker
3. Update
4. Select Version 7.0.3 (from lrusak's add-ons, not 7.0.108 from LibreELEC add-ons. That works fine.)

Observed behavior:
Add-on updated, and then
"docker error"

INFO: Python script stopped
-->End of Python script error report<--
ImportError: No module named oe
  import oe
File "/storage/.kodi/addons/service.system.docker/default.py", line 32, in <module>
Traceback (most recent call last):
Error Contents: No module named oe
Error Type: <type 'exceptions.ImportError'>
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

Sorry, kodi log uploader is also not working, so the above is transcribed by hand and may contain errors.

LibreELEC Version 7.0.2
Kodi 16.1 Git:c327c53

**Comment by phillipao** [comment]
Oh, I see that docker was deleted back in May. And I guess merged into LibreELEC? Would explain things if this update is from an older branch, but I don't know why I'm being offered the older update.

**Comment by phillipao** [comment]
Ok, I see it in their repo now. So I guess the issue is that your repo (I believe I installed the RPi2 one linked from your README.md) still offers its own, outdated Docker updates.

**Comment by lrusak** [comment]
The LibreELEC docker version should override the version here now.

**Comment by phillipao** [comment]
I'm seeing both versions offered.
