### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by andrewraj** [lrusak/lrusak-openelec-addons#14]
The repository links are broken. Will this work for Orange Pi?

**Comment by lrusak** [comment]
This repo is dead. And no, there is no support for the orange pi. Sorry.

**Comment by vulcanjedi** [comment]
So there is no way to install this Docker repo anymore for OE?

**Comment by lrusak** [comment]
No, use LibreELEC. Docker is available in the main LibreELEC add-ons repo
