### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by MrOnyx** [lrusak/lrusak-openelec-addons#2]
Connection Established 
when I check ip  does not change

here my config
client
dev tun
proto udp
remote nl.hide.me 3478
resolv-retry infinite
nobind
persist-key
persist-tun
ca /storage/.config/vpn-config/ca.crt
tls-client
remote-cert-tls server
auth-user-pass /storage/.config/vpn-config/pass.txt
crl-verify /storage/.config/vpn-config/crl.pem
comp-lzo
verb 1
reneg-sec 0
user nobody
group nogroup

here is my log
Tue Dec 29 11:48:12 2015 OpenVPN 2.3_git x86_64-openelec-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [IPv6] built on Nov 26 2015
Tue Dec 29 11:48:12 2015 library versions: LibreSSL 2.1.7, LZO 2.09
Tue Dec 29 11:48:12 2015 WARNING: file '/storage/.config/vpn-config/pass.txt' is group or others accessible
Tue Dec 29 11:48:12 2015 NOTE: UID/GID downgrade will be delayed because of --client, --pull, or --up-delay
Tue Dec 29 11:48:12 2015 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:12 2015 UDP link local: (not bound)
Tue Dec 29 11:48:12 2015 UDP link remote: [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:12 2015 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Dec 29 11:48:13 2015 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1542', remote='link-mtu 1557'
Tue Dec 29 11:48:13 2015 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Tue Dec 29 11:48:13 2015 WARNING: 'cipher' is used inconsistently, local='cipher BF-CBC', remote='cipher AES-128-CBC'
Tue Dec 29 11:48:13 2015 [*.hide.me] Peer Connection Initiated with [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:14 2015 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks 
Tue Dec 29 11:48:14 2015 TUN/TAP device tun0 opened
Tue Dec 29 11:48:14 2015 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Tue Dec 29 11:48:14 2015 /sbin/ip link set dev tun0 up mtu 1500
Tue Dec 29 11:48:14 2015 /sbin/ip addr add dev tun0 10.3.136.32/24 broadcast 10.3.136.255
ip: RTNETLINK answers: File exists
Tue Dec 29 11:48:14 2015 ERROR: Linux route add command failed: external program exited with error status: 2
Tue Dec 29 11:48:14 2015 GID set to nogroup
Tue Dec 29 11:48:14 2015 UID set to nobody
Tue Dec 29 11:48:14 2015 Initialization Sequence Completed
Tue Dec 29 11:48:19 2015 Authenticate/Decrypt packet error: cipher final failed
Tue Dec 29 11:48:24 2015 Authenticate/Decrypt packet error: cipher final failed
Tue Dec 29 11:48:29 2015 [*.hide.me] Inactivity timeout (--ping-restart), restarting
Tue Dec 29 11:48:29 2015 SIGUSR1[soft,ping-restart] received, process restarting
Tue Dec 29 11:48:34 2015 TCP/UDP: Preserving recently used remote address: [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:34 2015 UDP link local: (not bound)
Tue Dec 29 11:48:34 2015 UDP link remote: [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:35 2015 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1542', remote='link-mtu 1557'
Tue Dec 29 11:48:35 2015 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Tue Dec 29 11:48:35 2015 WARNING: 'cipher' is used inconsistently, local='cipher BF-CBC', remote='cipher AES-128-CBC'
Tue Dec 29 11:48:35 2015 [*.hide.me] Peer Connection Initiated with [AF_INET]46.166.179.33:3478
Tue Dec 29 11:48:36 2015 Option 'explicit-exit-notify' in [PUSH-OPTIONS]:6 is ignored by previous <connection> blocks 
Tue Dec 29 11:48:36 2015 Preserving previous TUN/TAP instance: tun0
Tue Dec 29 11:48:36 2015 NOTE: Pulled options changed on restart, will need to close and reopen TUN/TAP device.
ip: RTNETLINK answers: Operation not permitted
Tue Dec 29 11:48:36 2015 ERROR: Linux route delete command failed: external program exited with error status: 2
ip: RTNETLINK answers: Operation not permitted
Tue Dec 29 11:48:36 2015 ERROR: Linux route delete command failed: external program exited with error status: 2
ip: RTNETLINK answers: Operation not permitted
Tue Dec 29 11:48:36 2015 ERROR: Linux route add command failed: external program exited with error status: 2
Tue Dec 29 11:48:36 2015 /sbin/ip addr del dev tun0 10.3.136.32/24
ip: RTNETLINK answers: Operation not permitted
Tue Dec 29 11:48:36 2015 Linux ip addr del failed: external program exited with error status: 2
Tue Dec 29 11:48:37 2015 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
Tue Dec 29 11:48:37 2015 Exiting due to fatal error

**Comment by lrusak** [comment]
Are you checking your IP in the kodi interface? or with my ipinfo utility?

**Comment by MrOnyx** [comment]
i checking with your ip info utility

**Comment by lrusak** [comment]
Not sure, have you tried this config file on another machine?

I run my own openvpn server and in my server config I have this option
```push "redirect-gateway def1 bypass-dhcp"``` This option is described as

> If enabled, this directive will configure all clients to redirect their default network gateway through the VPN, causing all IP traffic such as web browsing and and DNS lookups to go through the VPN (The OpenVPN server machine may need to NAT or bridge the TUN/TAP interface to the internet in order for this to work properly).

This is the client config I use (I use inline keys, but this shouldn't be an issue)
```
client
dev tun
proto udp
remote vps.xxxxxx.com 1194
resolv-retry infinite
nobind
user nobody
group nogroup
persist-key
persist-tun
;ca [inline]
;cert [inline]
;key [inline]
compress lz4
verb 3
redirect-gateway def1
key-direction 1

<ca>
ca goes here
</ca>

<cert>
cert goes here
</cert>

<key>
key goes here
</key>

<tls-auth>
tls-auth key goes here
</tls-auth>
```
