### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by ajvirus** [lrusak/lrusak-openelec-addons#3]
i followed the instructions on http://openelec.tv/forum/unofficial-openelec-addons/79148-openvpn-lrusak-repo

but i cant get it to work, do i need to use this & follow the whole hornsby guide? because when i run the openvpn command its not found.

i dont see the connection established pop-up

Openvpn server log 

20160107 19:42:58 1 variation(s) on previous 3 message(s) suppressed by --mute 
20160107 19:42:58 D MANAGEMENT: CMD 'status 2' 
20160107 19:42:58 MANAGEMENT: Client disconnected 
20160107 19:42:58 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:42:58 D MANAGEMENT: CMD 'status 2' 
20160107 19:42:58 MANAGEMENT: Client disconnected 
20160107 19:42:58 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:42:58 D MANAGEMENT: CMD 'log 500' 
20160107 19:42:58 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 D MANAGEMENT: CMD 'state' 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 D MANAGEMENT: CMD 'state' 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 D MANAGEMENT: CMD 'state' 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 NOTE: --mute triggered... 
20160107 19:49:08 1 variation(s) on previous 3 message(s) suppressed by --mute 
20160107 19:49:08 D MANAGEMENT: CMD 'status 2' 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 D MANAGEMENT: CMD 'status 2' 
20160107 19:49:08 MANAGEMENT: Client disconnected 
20160107 19:49:08 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:14 
20160107 19:49:08 D MANAGEMENT: CMD 'log 500'

**Comment by lrusak** [comment]
You can use my VPN add-on standalone. Perhaps you just need to restart the SSH session so the session knows about the updated ```PATH```.

What does the client log show? ```/var/log/openvpn.log```

**Comment by ajvirus** [comment]
great! i found i missed a </key> and it works great!! thanks!!

now i use ;push "redirect-gateway def1" at work to push all traffic through vpn, put this doesnt like the push command what can i do for this?

**Comment by lrusak** [comment]
```push``` commands go in the server config.

In the client config you would just need ```redirect-gateway def1```
