### ISSUE TITLE
docker addon fails because overlayfs is not available

### ISSUE THREAD

**Issue by edgard** [lrusak/lrusak-openelec-addons#4]
So, I found your addon and I love you already, but I'm unable to run it on OE 6.0 because apparently there is no overlayfs support.

Any tips on how to run it? (X64)

**Comment by lrusak** [comment]
OpenELEC 6.0 Generic has the nessesary kernel config
OpenELEC 6.0 Nvidia_Legacy does not.

OpenELEC 6.0.1 will have the kernel configs in sync, and hopefully will be released soon.

If you are running the Generic build then something else is wrong.

**Comment by edgard** [comment]
Yeah, i was using nvidia_legacy. Thanks. Just tested a newer Milhouse build and it works as intended.

Thanks!
