### ISSUE TITLE
Unable to launch enabled Add-on

### ISSUE THREAD

**Issue by ChuckRpi2** [lrusak/lrusak-openelec-addons#6]
I already had Unofficial OpenVPN installed on my Rpi2.  I have a PureVPN account which works on my Win7 desktop on another machine.  I copied your zip to my Pi's home/downloads and installed from zip.  This looked normal (bottom right screen showed installed & enabled).  I then went to System->Add-ons and it shows lrusak's OpenELEC (RPi2/arm) Add-on - Enabled. On the Addon screen I am unable to select the LAUNCH (only disable & uninstall).  I am using OpenElec/Kodi 15.0-RC1 (Jul 1 2015).

Any help would be great.

**Comment by lrusak** [comment]
You don't launch a repo ;)

You need to install the OpenVPN add-on from the repo,

http://openelec.tv/forum/unofficial-openelec-addons/79148-openvpn-lrusak-repo

**Comment by ChuckRpi2** [comment]
Thank you for your response.  My problem was not being at OpenElec 6 version.  After reading more carefully the comments on your OpenElec post, I updated my OpenElec with 6.0.1 then tried again.  It work perfectly.I will comment to this effect on the GitHub as well.
Again thanks for responding and A big thanks for making using PureVPN so simple to use on my Pi. 

    On Sunday, February 7, 2016 2:48 PM, Lukas Rusak <notifications@github.com> wrote:
 

 You don't launch a repo ;)You need to install the OpenVPN add-on from the repo,http://openelec.tv/forum/unofficial-openelec-addons/79148-openvpn-lrusak-repo—
