### ISSUE TITLE
OpenVPN broken under LibreElec

### ISSUE THREAD

**Issue by Darren-Hill** [lrusak/lrusak-openelec-addons#7]
Just switched over from OE to LE, and the OpenVPN add-on is giving errors as it seems to rely on specific OE modules:

`20:22:22  38.053425 T:1807741856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named oe
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.network.openvpn/default.py", line 33, in <module>
                                                import oe
                                            ImportError: No module named oe`

Tried the obvious swap of oe for le and it fails, so I guess this add-on is going to need a re-write or new version for use in LibreElec? It's a very handy add-on for travellers like me, so would love to see a version working with LE too.

**Comment by lrusak** [comment]
change the following line in default.py
```
sys.path.append('/storage/.kodi/addons/service.openelec.settings')
```
to
```
sys.path.append('/storage/.kodi/addons/service.libreelec.settings')
```

I'll update all my add-ons soonish

**Comment by Darren-Hill** [comment]
Thanks, worked a treat.

All is good again, closing this off.

**Comment by kenvip** [comment]
OpenVPN addon does not work in LibreElec 7.9. Made recommended changes above as well as changed the os.openelec.tv to os.libreelec.tv in the addon.xml. it says "Establishing Connection" and nothing happens. Please help.

`<requires>
    <import addon="os.libreelec.tv" version="7.9"/>
    <import addon="xbmc.python" version="2.1.0"/>
  </requires>`

**Comment by sscraggles** [comment]
I'm also trying to run on LibreElec 7.9.  I've made the change to default.py, but it seems the openvpn binary is compiled against an earlier version of ssl than included with 7.9..

`error while loading shared libraries: libssl.so.35: cannot open shared object file: No such file or directory`

**Comment by sscraggles** [comment]
Seems the openvpn binary is now part of the LibreElec 7.9 build, so this additional change allows the addon interface to function...

I changed the path to the binary in line 64 of the default.py file from 
`oe.execute('/storage/.kodi/addons/service.network.openvpn/bin/openvpn --daemon --writepid /var/run/openvpn.pid --log /var/log/openvpn.log --config ' + self.get_config_file() + ' ' + self.get_custom_options())`
to
`oe.execute('/usr/bin/openvpn --daemon --writepid /var/run/openvpn.pid --log /var/log/openvpn.log --config ' + self.get_config_file() + ' ' + self.get_custom_options())`

**Comment by kenvip** [comment]
Thanks for the solution. It works as expected now.
